### ISSUE TITLE
Small issue in power-menu.sh, easily fixed

### ISSUE THREAD

**Issue by mrHeavenli** [tostiheld/dotfiles#1]
The $ on line 16 makes the first option in the power-menu unusable as well as putting a dollar sign in front of it. The script also works without the $.

**Comment by tostiheld** [comment]
It's been working fine for me for years. I just checked, and I'm still using the same power menu script, even though the rest of my DE these days is nothing like what's in the repository here. Feel free to adjust in your own version 🤷. This repository was just meant as inspiration, so I won't be taking any pull requests.

**Comment by mrHeavenli** [comment]
Sure, I figured as much. Just in case anyone encounters the problem I had :)
